composer.json

This pull request upgrades collision to the latest version.

Upgrade collision to the latest version

---

resources/sass/_footer.scss

fix footer links not displayed correctly

---

resources/js/app.js
resources/sass/_docs.scss

Added the section link javascript & styles

Add section hashtag links

---

resources/sass/_footer.scss

Remove overflow hidden on footer_nav_contain class

---

resources/sass/_footer.scss

Reverts laravel/laravel.com-next#31

Revert "Remove overflow hidden on footer_nav_contain class"

---

resources/sass/_header.scss

Vertically center the nav links, search, and logo

---

resources/views/docs.blade.php

I replaced the hardcoded HTML with actual script to track impressions, clicks, and revenue.
There is no details on how to compile and preview on the local machine, so you may want to test it and make sure it works before merging the PR.

Fix Carbon Integration

---

public/css/app.css
public/js/app.js
public/mix-manifest.json
resources/sass/_docs.scss
resources/sass/_prism.scss
resources/sass/_typography.scss

- Slightly lessen docs body text line height
- Slightly increase font weight on docs code blocks
- Slightly lighten code blocks background color
- Add soft bottom border to code blocks to help them stand out
- Add base font size of 16px so all em/rem calculations are consistent
Co-Authored-By: Jake Bathman <jake.bathman@gmail.com> @jakebathman

Make minor tweaks to docs colors for accessibility

---

resources/sass/_docs.scss

It will be easier to read code if we can increase the font size.

Increase code block font size

---

resources/js/docs.js

Small tweak to collapse the sidebar element if its currently active

Click to collapse sidebar element if currently  active

---

resources/sass/_docs.scss

Adds space / aligns with logo when clicking anchor links
| before | after |
| - | - |
|  ![before](https://user-images.githubusercontent.com/29180903/63646239-64a33380-c6dd-11e9-9c9e-7e1dee28ab12.png) | ![after](https://user-images.githubusercontent.com/29180903/63646208-0fffb880-c6dd-11e9-85fc-8ce5ad2d4bbf.png) |

Add space on anchor links

---

resources/sass/_docs.scss

continuation of #58 
- Made anchors block elements for safari
- WIP to address other possible fixes needed

Safari anchor fixes

---

resources/sass/_base.scss

fix tablet horizontal scroll

---

resources/sass/_header.scss

Enhance the drop contain in small screen size

---

resources/views/docs.blade.php
resources/views/partials/header.blade.php
resources/views/partials/layout.blade.php

Changes made :
* Adding aria-label tags for fields without a label
* Zoom authorization in the meta viewport tag

Improvement of the site's accessibility

---

composer.json
composer.lock

Upgrades `erusev/parsedown-extra` to V0.8.0. 
The upgrade takes care of this error
`Trying to access array offset on value of type null` [More](https://github.com/erusev/parsedown-extra/issues/140#issue-536612600)

Support for PHP 7.4

---

public/css/app.css
public/js/app.js
public/mix-manifest.json
resources/sass/_search.scss
resources/views/partials/algolia_template.php

This adds lower level in the hierarchy to allow having better relevance
before:
after:

Improve search display for some queries

---

app/Exceptions/Handler.php
app/Http/Controllers/Controller.php
app/Http/Kernel.php
app/Http/Middleware/Authenticate.php
app/Http/Middleware/RedirectIfAuthenticated.php
app/Http/Middleware/TrustProxies.php
app/Http/Middleware/VerifyCsrfToken.php
app/Providers/AuthServiceProvider.php
app/Providers/EventServiceProvider.php
app/Providers/RouteServiceProvider.php
composer.json
composer.lock
config/app.php
config/auth.php
config/cache.php
config/database.php
config/filesystems.php
config/logging.php
config/mail.php
config/queue.php
config/services.php
config/session.php

This PR updates the codebase from Laravel 5.8 to 7 🎉

Update to Laravel 7

---

resources/views/docs.blade.php
routes/web.php

See https://github.com/laravel/framework/issues/32484

Add a note for older doc versions

---

resources/views/partners/kirschbaum-development-group.blade.php

Updated copy from our marketing director

Kirschbaum partner page - copy update

---

build/doctum/composer.json
build/doctum/composer.lock

Upgrade Doctum to 5.3.0

---

resources/css/_prism.css
resources/css/_typography.css

- #153 introduced an always constant scroll bar on windows browsers
- Wraps long links

Fix long links/code tags on smaller devices

---

resources/js/docs.js

The "installation" navbar item is automatically activated on the root page.

Activates the navbar item on the root page

---

resources/views/partials/header.blade.php

For some reason these two titles were bigger

Project title uniform

---

resources/views/docs.blade.php
resources/views/partials/header.blade.php

Show keyboard shortcut to search field

---

routes/web.php

Took me a month to notice this.

Small trivia typo 😆 

---

resources/views/partials/footer.blade.php

Hi @taylorotwell,
Added: WebReinvent in Partners
Hope to get your approval soon.
Thanks

Added: WebReinvent in Partners

---

app/Parsedown.php

not sure what that was doing in there.

remove unused variable

---

build/doctum/composer.json
build/doctum/composer.lock

See: https://github.com/code-lts/doctum/releases/tag/v5.5.0
This release should improve network performance by a lot. See: https://github.com/code-lts/doctum/issues/43#issuecomment-1008338523

Upgrade Doctum to 5.5

---

README.md

`laravel.com` instead of `laravel.com-next`

fix repository name

---

public/img/favicon/browserconfig.xml

https://realfavicongenerator.net/favicon_checker?protocol=https&site=laravel.com%2F#.Yh3Kd-jP23A

fix path mstile

---

app/Documentation.php
app/Http/Controllers/DocsController.php
routes/web.php

See: https://github.com/laravel/framework/pull/43357
[Example endpoint data](https://github.com/laravel/laravel.com/files/9178424/pages.json.txt)

Add JSON representation of the docs for the artisan docs command

---

resources/views/components/search-modal.blade.php

This does what #240 intended to do (but I put the handler in the wrong spot on that PR).
This does not remove the wrong handler as that's already covered by #250.

Fix modal not closing on same-page results

---

resources/css/_search.css

Matches link color in docs. 
| Before | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1423115/230006333-13b56258-fd0b-4c87-898d-26837eb986c0.png)  | ![image](https://user-images.githubusercontent.com/1423115/230006364-c0d18b58-fd5b-490b-beb5-df0e0e751db4.png) |

Tweak red color in search

---

resources/views/frontend.blade.php

Fixed a typo and added Laravel bootcamp as reference.

Update some texts

---

resources/views/partials/footer.blade.php
resources/views/partials/header.blade.php

Add links to the https://laravel.bigcartel.com/ site in the header and footer.

Add Shop links

---

resources/views/partials/footer.blade.php

Add a link to [https://larabelles.com](https://larabelles.com) to the footer.

Add link to Larabelles

---

composer.json
composer.lock

This PR bumps dependencies to their latest minor/patch releases and removes the MIT license reference in composer.json

Update dependencies and remove license

---

resources/views/components/header-news-bar.blade.php

**Remove Laracon AU:**
- Removed Laracon AU from the event list as it has been successfully completed.
**Add Laracon India:**
- Added Laracon India to the event list to reflect the availability of tickets.

Update Header Add Laracon India

---

resources/views/components/header-news-bar.blade.php

This PR fixes an incorrect href url.

Fix incorrect href url

---

routes/web.php

Remove unused constants

---

bin/checkout_latest_docs.sh

This will make much faster clone of the docs repo.

use --depth for faster clone

---

resources/views/components/header-news-bar.blade.php

Remove laracon us!

---

resources/views/trademark.blade.php

It seems like the trademark form had some copy and paste values. This updates the values accordingly to their corresponding label.
(Sorry for the tailwinds auto formatting on save...)

Use different values in trademark form

---

resources/views/components/header-news-bar.blade.php

Add Nightwatch to the news banner

---

routes/web.php

temporarily redirecting redirects to a signup form until we can create a meetup directory

redirecting /meetups to a form for now
