laravel/laravel.com

app/Http/Controllers/DocsController.php
composer.json
composer.lock
resources/views/app.blade.php

Add relevant HTML title to docs pages.

Added titles to docs pages

---

resources/assets/sass/components/_buttons.scss
resources/assets/sass/components/_footer.scss
resources/assets/sass/components/_nav.scss
resources/assets/sass/components/_panels.scss
resources/assets/sass/components/_sidebar.scss
resources/assets/sass/components/_slide-menu.scss
resources/assets/sass/content/_404.scss
resources/assets/sass/content/_docs.scss

- Removed unnecessary CSS
- Removed !importants
- Less nest
- Better practices
- Cleaned trailing spaces

Improve SCSS

---

public/assets/js/laravel.js
resources/assets/js/laravel.js

Revert breaking jquery change to docs headers.

---

resources/views/partials/main-nav.blade.php

Adds link to Laravel Podcast to Community dropdown

---

resources/views/app.blade.php

add alt to Laravel logo (w3c)

---

resources/views/marketing.blade.php

add alternative to Picture Laravel logo

add alternative to Picture (w3c)

---

resources/views/marketing.blade.php

add alternative name to Picture white logo (w3c)

add alt to Picture white logo (w3c)

---

resources/views/partials/algolia_template.php

fix missing clear

---

resources/views/marketing.blade.php

Since the docs have moved to github, there´s no working link.

Changed Socialite URL

---

resources/views/partials/main-nav.blade.php

Lumen supported https, I change lumen link on navbar.

Update https link

---

app/Services/Documentation/Indexer.php

Hey,
We have improved the relevance on documentations search since I did the initial PR for the laravel documentation.
So this PR brings those improvements to make the overall search experience better. It will mostly allow to have more various set of results (see screenshots) and be more relevant at the same time.
I also took the opportunity to do some small refactoring on the indexing code.
--------
Before:
After:

Improved relevance + Refactoring

---

app/Http/Controllers/DocsController.php

Looks like you forget to add a couple of parameters to phpDocumentator block

Add @param's to docblock

---

resources/views/partials/algolia_template.php

Not sure if this was intentional but we'll see :)

Update Algolia 'powered by' URL

---

resources/views/marketing.blade.php

@taylorotwell it'd be cool if we could switch between various projects each week or something :)

Link to Cachet

---

resources/views/marketing.blade.php

Update marketing.blade.php with missing 'on'

---

resources/views/partials/main-nav.blade.php

Add Laracon Online to Conference dropdown of main navigation bar.

Add Laracon Online to Conference dropdown

---

resources/assets/js/laravel.js
resources/assets/sass/components/_slide-menu.scss

Fixed an issue where the slide menu is not displayed at medium sizes.

fix slide menu on medium sizes

---

resources/assets/js/laravel.js

Close an expanded list when clicking on the title.

enhance to close list when expanded

---

resources/assets/sass/components/_nav.scss

An enhancement for the vertical clickable area around the nav items, plus adding a border on hover.

enhance the hover effect for nav items

---

resources/views/app.blade.php
routes/web.php

This fixes an issue with the version not being set on the 404 page and individual partner pages, causing the search not to work.

Added default documentation version for Algolia search.

---

build/sami/sami.php

We're missing those awesome API docs. 😄

Add Laravel 5.5 API docs

---

resources/assets/js/laravel.js

Check #doc-expand exists

---

resources/views/marketing.blade.php

Update Forge info

---

composer.json
composer.lock
config/app.php
config/hashing.php
config/logging.php

I feel that as the flagship of Laravel, it's own website should be running the latest version :)
This is a simple upgrade to 5.6
I've tested it locally and it works on my machine (including the docs).

Upgrade Laravel.com to 5.6

---

resources/views/community-partner-kirschbaum.blade.php

Updated email and Github organization link.

Kirschbaum Development Group - Link Updates

---

build/api.sh

Should finally fix https://github.com/laravel/docs/issues/4117

Delete old api folder before copying new one

---

public/assets/css/laravel.css
public/assets/js/laravel.js
public/mix-manifest.json
resources/assets/js/laravel.js
resources/views/app.blade.php

Same behavior before and after, 25kb removed from transfer.
Network before:
Network after:

Remove Vue from app

---

public/assets/css/laravel.css
public/assets/js/laravel.js
public/mix-manifest.json
resources/assets/js/laravel.js
resources/views/app.blade.php

Referenced here: https://github.com/laravel/laravel.com/pull/203
Fixed without re-adding Vue.

Fix algolia result width

---

app/Http/Controllers/DocsController.php

Reverts #206 
See https://github.com/laravel/laravel.com/pull/206#issuecomment-452099835

Revert #206

---

resources/views/app.blade.php

I  have changed doctype to uppercase from lowercase In the app.blade.php

Uppercase doctype

---

resources/views/partials/main-nav.blade.php

Added Discord URL to footer nav bar

Added Discord URL
