laravel/laravel.com

resources/sass/_partners.scss
resources/views/partners.blade.php

On partners page https://laravel.com/partners there is a horizontal scrollbar caused by the video's container position.
This PR fixes that issue.

fix horizontal scrollbar on partners page

---

resources/js/docs.js
resources/sass/_sidebar_layout.scss

This PR will fix that the docs sidebar is expanding on each request, happening in google chrome.
Hope it's better now.

fix docs sidebar expanding on each request

---

resources/sass/_sidebar_layout.scss

Make the navbar sticky to keep it in view at all times when scrolling.
This _may_ be a problem if the window is too short vertically. I would be willing to work on a solution for this (perhaps allowing the nav to be scrollable in that case) but wanted to get opinions on this before investing more work into it.
This does _not_ affect the nav bar when on mobile.

Make nav bar "sticky"

---

resources/sass/_docs.scss

Didn't realize the h4 ie validation styles were effected by https://github.com/laravel/laravel.com-next/pull/10
example: https://laravel.com/docs/5.8/validation#rule-after
although maybe a global reset would be better?
sorry 😅

Add h4 link color

---

resources/sass/_footer.scss

The telescope link in the footer is cut, it needs more space so the full word 'Telescope' would be visible

Fix: the Telescope link in footer

---

resources/sass/_sidebar_layout.scss

On Google Chrome, Windows 10:
When using the `position: sticky;` style, there's currently a bug that makes the text blurry in the sticky container if the `top` is not a round number of pixels.
This stylesheet uses relative em units which causes the top to be 10.4px. When setting the top to 10px, the text is sharp again!
I've also tested this on Firefox, Edge and IE, where it's not an issue. So far I've only found [this webkit issue](https://bugs.webkit.org/show_bug.cgi?id=159428) that even begins to explain it.

Fixes blurry text in the sidebar

---

resources/js/app.js
resources/js/docs.js
resources/sass/_docs.scss
resources/sass/_partners.scss
resources/sass/_styles.scss

- removed styles for `.docs_nav` in `resources/sass/_docs.scss` as that element is not present in the actual site and the relevant JS is commented out as well
- removed JS and SASS code that was commented out

Cleanup of JS and SASS resources

---

resources/sass/_docs.scss

This makes more of the TOC to be visible at once and brings the actual content closer.
Currently it's okay for pages with a short TOC, but in some cases I have to scroll quite far across spread out items to reach the actual content https://laravel.com/docs/5.8/eloquent

Condense the table of contents

---

resources/sass/_sidebar_layout.scss

`position: sticky; top: 0;` is my quick hack to make `.sidebar` fixed without taking it out of flow. I am not that great at CSS but I feel this is a bit of emergency as some chapters are pretty hard to access on a small screen.
I have to zoom out to 67% to reach bottom of "Digging Deeper" at the current design. But other people might not guess that there's anything below and wouldn't even try zooming out.

Make menu scrollable on desktop

---

resources/views/marketing.blade.php

Right now, the **Learn More** button under **Resources** on the homepage (`marketing`) doesn't go anywhere.
Until a resources detail page is added, the button can be removed.
Let me know if you'd like this done differently or have any feedback. Thanks!

Remove the Learn More button under Resources

---

bin/checkout_latest_docs.sh
bin/setup.sh
bin/update.sh
readme.md

- Add bin script for setup
- Add bin script for update
- Add readme instructions for setting the repo up locally using bin scripts
Co-Authored-By: Jake Bathman <jake.bathman@gmail.com> @jakebathman

Add bin scripts and instructions

---

resources/sass/_docs.scss

It is really hard to read the docs when compared with the previous.
The generally accepted UX principle is to have 1 rem font size at least for paragraph.

Increase docs paragraph font size to 1rem

---

resources/sass/_header.scss

Similar to #42 , the `scale(1.03)` hover animation in the main header nav looks jenky in webkit browsers.
This pull request changes `scale` to `scale3d` and adds `perspective(1px)` to smooth the animation more. The text is slightly blurred in the hover state but I don't believe there's a fix for that.
Demo:
https://giphy.com/gifs/cM7burmgPSZslfFEcI

Reduce hover animation jenkiness in header nav

---

resources/views/docs.blade.php

HTML was invalid due to a useless quote, plus `selected="yes"` is not valid, it should be either `selected` or `selected="selected"`.
**Before:**
**After:**

Fix version switcher

---

resources/views/marketing.blade.php
resources/views/partials/layout.blade.php

Seems like these were accidentally dropped with the new design.

Re-add Laracon EU and AU websites

---

resources/views/partials/layout.blade.php

The current link leads to a 404. This replaces the 404 link with the correct link.

Fix "ABOUT YOU" link

---

resources/views/partials/layout.blade.php

Changes the call to action on global `partners` footer when on  `/partners`
Before, also linked to `/partners`.. now links to google form.

Change footer button on partners page

---

resources/sass/_docs.scss

Same goal as PR #64. Changed removal of the underline to only target the unordered list in the .content-list on the docs page instead.
Here's a few screenshots.

Remove underline only from .content-list ul, bump font size to match.

---

resources/js/app.js
resources/views/partials/layout.blade.php

Mousetrap is a great library, but I do not see the point to include it if is used only for a single key binding.
This PR saves ~2KB and a network request.

Removed Mousetrap dependency as it is used only for a single key binding

---

resources/sass/_base.scss

Add webkit-overflow-scrolling: touch to fix scrolling issues on touch devices
This fixes this issue: https://twitter.com/joseph_silber/status/1168933957305544704

Improve scrolling on webkit mobile devices

---

resources/sass/_sidebar_layout.scss

This fixes a visual bug in Firefox Dev Edition (70.0b2 64-bit) on macOS.
The same line height in Chrome appears fine as well. There was a bit of overflow in FF and the last item in a sidebar list was cut off.

Add line height to docs sidebar a tags

---

resources/sass/_sidebar_layout.scss

With the old `max-height: 28em;` a sidebar section of the documentation with too many items (in my test setup, over 12) wouldn't display all of the items.
Removing the max height on the opened UL element fixes it.
Live example of the issue fixed by this commit : 
https://laravel.com/docs/5.1/mail

Fix sidebar sections with too many items

---

resources/views/marketing.blade.php
resources/views/partials/header.blade.php
resources/views/partials/layout.blade.php

Currently, in the 'Ecosystem' dropdown and when you click on the one for Horizon it goes to `horizon.laravel.com` which just redirects to the `laravel.com` homepage. 
I've updated this so that it now links to Horizon's documentation page.

Fixed link to Horizon in Ecosystem dropdown

---

app/Documentation.php
app/Http/Controllers/DocsController.php
resources/views/docs-missing.blade.php

There are a number of pages that have come and gone in the documentation's lifetime. There are dozens of examples I could list, but here's a few:
* 4.2 had a page on the [IoC container](https://laravel.com/docs/4.2/ioc) which was later renamed to the [Service Container
](https://laravel.com/docs/6.x/container).
* 5.0 to 5.3 had pages on [Elixir](https://laravel.com/docs/5.0/elixir) before that was renamed to [Mix](https://laravel.com/docs/6.x/mix).
* 5.1 and 5.2 included a [short tutorial](https://laravel.com/docs/5.1/quickstart) which was dropped from the documentation. 
This PR improves the 404 page by looking at other versions of the documentation and checking if the page existed in some other point in time. If it does, then links are included to those versions. If not, then current …

Better 404s

---

resources/sass/_footer.scss

Footer ecosystem column max-height set to 33rem. In Firefox 73.0 on macOS telescope's half is not visible. You can see it in the attached file.
This PR fixes this problem increasing max-height to 34rem.

max height increased for footer nav contain

---

resources/sass/_typography.scss

[Inspiration](https://twitter.com/SadeghPM/status/1228190212158672896).
This PR removes horizontal margin of blockquote elements on smaller screen sizes thus increasing readability.
Breakpoint of 40em was chosen based on another usage of the `fl-break-max` mixin [here](https://github.com/laravel/laravel.com-next/blob/master/resources/sass/_docs.scss#L64). Added the changes to `_typography.scss` since I found other references to blockquote in that file.
Before (left) and after (right):
Have a great day!

Remove blockquote horizontal margin on smaller screens

---

build/docs.sh
build/sami/sami.php

https://laravel.com/api/5.5/ was recently removed, but it should be available at least until August 2020 when it's LTS support ends.

Add 5.5 back (supported until Aug 2020)

---

resources/views/marketing.blade.php

I noticed the "Laracon Online is February 26th" banner was showing on the home page.  The update simply comments out the banner which looks to be how a prior banner was removed.  I figured this may help out. (Though not 100% sure this is the best workflow).  Keep up the great work!

Hide Laracon Online Feb 26 banner on homepage

---

resources/sass/_pages.scss

Fix hero banner on tablet home page
Before:
After:

fix hero banner on tablet

---

resources/views/partials/layout.blade.php

This brings back the canonical link which was present in the previous version of the Laravel website:
https://github.com/laravel/laravel.com/blob/01c9b5a0cf969cba615eacb7f8af9dd9ed980321/resources/views/app.blade.php#L11-L13
Related to: https://twitter.com/stoicseal/status/1244426084776624135

Add canonical link

---

resources/css/_prism.css

The `<code>` tag causes a horizontal scroll on mobile devices when its content is too long (eg: [Sanctum documentation page](https://laravel.test/docs/8.x/sanctum)). See the screenshot above:
I added CSS attributes to the tag being careful not to break the alignment with the rest of the textual content.

Fix the `<code>` tag overflow on mobile resolution

---

resources/css/_accessibility.css
resources/css/app.css
resources/js/app.js
resources/js/components/accessibility.js
resources/views/components/accessibility/main-content-wrapper.blade.php
resources/views/components/accessibility/skip-to-content-link.blade.php
resources/views/docs.blade.php

The link allows screen readers and keyboard users to quickly jump over the main navigation. It's a recommended accessibility feature from the [Web Content Accessibility Guidelines 2.1, Section 2.4.1: Bypass Blocks](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html). I primarily navigate the web with my keyboard, so this would save me from hitting the tab key a bunch of times on the docs page.
The user currently must tab through ~90 elements before arriving at the main content. Check the bottom left corner of the gif below to see the links that are being tabbed through.
The link only appears when it has focus, allowing the user to bypass the main navigation.
If this request is accepted, I'd like to add this feature to the site's other pages. I've left the other pages off of …

Accessibility: skip-to-content link in docs

---

build/api.sh
build/doctum/composer.json
build/doctum/composer.lock
build/doctum/doctum.php

Read the news: https://github.com/code-lts/doctum/releases/tag/v5.4.0
I added a bunch of features that support tags you use, like `@mixin` for example
Commits:
- Upgrade Doctum to 5.4 (af4b6ed603b7a805290c080d2d64d23b471ae397)
- Enable verbose on Doctum script (fc18ee975b172a661eec87075060cfc8f79994a1)
- Enable support for base_url (b251a3e0c626729b29dd4037fad938270f6b1b8f) (This will enable [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) and allow you to start searching in documentation from your search bar!)
- Enable exit mode and ignore parse errors (ae2408d81b31c483d175f12fde77a9fe1664825b)

Upgrade Doctum to 5.4

---

resources/views/docs.blade.php

This PR updates vertical navigation with horizontal navigation, which gives more space for the documentation itself.
Before             |  After
:-------------------------:|:-------------------------:

Update mobile nav for docs

---

resources/css/_prism.css

Follow-up to #153 (and the subsequent #154).
On browser Pale Moon, the code tags are shifted up, which makes reading the documentation quite tedious. That seems to be because Pale Moon applies a different default baseline, closer to the specifications, than Firefox and Chrome.
For more details you may read [this topic](https://forum.palemoon.org/viewtopic.php?f=70&t=26935) on Pale Moon forum.

Fix code tags alignment on browsers that use different default baseline

---

resources/css/_carbon_ads.css

When the pages are printed, the carbon ad gets in the way, so I updated the CSS to hide the Carbon Ad when printing the page.

Added "print" media query

---

resources/views/docs.blade.php

Accessibility fix - the HTML `label` element associated with the document version switcher `select` tag didn't match, so I fixed it.

Fixed version switcher label `for` attribute

---

resources/views/docs.blade.php

When using the documentation, i  wanted to click the search bar but i realised it wasn't long enough and you actually have to click on the search text to get it working
i have extended the width of search bar by add .w-full to the button on line 222 so that you can click on the white space after the search bar and still get the search modal.

Full with search button in docs.blade.php

---

README.md

The new laravel.com site requires a Torchlight token to run locally. This PR updates the readme to include a paragraph that points user to the torchlight.dev site to claim a token.

Updating readme to include instructions on how to setup torchlight

---

routes/web.php

- Removes two hard coded partner redirects as they follow the general partner redirect format
- Consdenses a redirect block to use `Route::redirect()`

Cleaning up routes

---

routes/web.php

The string version of the framework has been replaced with a constant

String version has been replaced with a constant

---

resources/views/components/search-modal.blade.php

The issue:
1. Open a documentation page, e.g. https://laravel.com/docs/9.x/releases
2. Search for something that's found on that page, e.g. click `/` and type `Versioning`
3. Select the result and observe that page in the background scrolls to the result, but the overlay remains.
This behaviour is slightly confusing as the UX is different from the other searches and less attentive users might even conclude that "nothing is happening".
I've added a handler that closes the modal on click (it also handles keyboard navigation with Enter). I've tried out multiple scenarios locally and it appears to me that everything works as expected.
There is a slight visual change when the search result leads to another page. Previously the pages swapped with modal visible on the previous page the entire …

Fix modal not closing on same-page results

---

resources/views/partials/layout.blade.php
resources/views/partials/theme.blade.php
routes/web.php

Hi! I noticed the Laravel website was not taking the current theme into account to show matching scrollbars and browser UI (where supported), so i went ahead and improved it.
This is what im talking about: 
<div align="center">
</div>
As you can see, the top of the Safari app, and the scrollbar on Windows is not matching the site current theme, which in the photos is "dark". 
I added the necessary meta tags to make all of this react to the current theme, i also took care and made it so this changes dont affect the landing ('/') and team ('/team') page as this page's design is not ready for dark mode. Basically this pages now have a "forced" light mode. No changes there.
Here is how it looks:
Dark mode:
<div align="center">
</div>
Light mode:
<div align="center">
</div>
I've tested it and …

Managing color-scheme and theme-color meta tags based on current theme for better visuals

---

resources/views/partials/theme.blade.php

This is a fix for a bug i introduced in the last pull request 😑
If you select the 'system' theme and then you manually change your OS theme to light mode or viceversa, you will see this:
I forgot to update the meta tags when the user manually changes his OS theme and has the 'system' theme selected, using the JS event we were already using
This PR fixes it :)

Fixed a bug where the color-scheme and theme-color meta tags arent updating when on 'system' theme and the user changes his OS theme manually

---

resources/js/components/search.js

Following the same shortcut key for opening the search option. 
https://vitejs.dev/
https://tailwindcss.com/

add support for ctrl + k to open search in docs

---

resources/views/components/search-modal.blade.php

This PR reverts #240 as it has broken the search on mobile and, to some extent, on desktop as well.
The event listener was applied to the search input meaning that any click on the text input will close the modal.
https://user-images.githubusercontent.com/24803032/184752545-a9202afd-3772-4768-a3e9-cfe348417fdc.MP4
I'm guessing this event listener was intended to be applied to the items in the result list instead of the text input, but I can't test it locally so I am just gonna revert this and we can follow up with another PR for the original improvement with feedback from @tontonsb.

revert #240; breaks searching on mobile.

---

resources/js/components/search.js
resources/views/components/search-modal.blade.php

On the current website, for any fresh search I always see a flash of:
> "We didn't find any result for 'MY_QUERY_HERE'. Sorry!"
in the result box while the results are loading and then the results for the query are shown.
This adds a new state to show "Searching..." when there are no results but a query is still in flight.
Here is a video showing the problem:
https://user-images.githubusercontent.com/24803032/190534854-ca1bdae3-1719-4b1d-a036-af92b74e0dc4.mov
I don't have a valid Algolia key, so I haven't been able to 100% confirm this fix.

fix flash of 'no results' when searching

---

composer.json

Parsedown is no longer being used since https://github.com/laravel/laravel.com/pull/205 and can therefor be removed.
It was previously used in `app/Documentation.php`
You will still need to run `composer update`
(In the following days I will create follow up PRs to upgrade to Laravel 9, PHP 8.1 and Vite if that is wanted)

Remove unused Parsedown

---

resources/js/docs.js

Fix a regression that causes the support policy highlight style to no longer apply.
This happened because the table is now wrapped in a div.

Support policy highlight style doesn't apply

---

resources/js/docs.js

PR #269 broke the highlight styles for <=v9 documentation branches because they still use the old dom structure which doesn't contain the table overflow fix.
It's easier to maintain backwards compatibility than to go back and change all the <=v9 branches.

Fix support policy highlight style for <=9 documentation branches

---

routes/web.php

I constantly get bit by a 404 each time I try and visit https://laravel.com/docs/cashier
This PR adds redirects to redirect `/docs/cashier` to `/docs/billing`, and `/docs/{version}/cashier` to `/docs/{version}/billing`

Add Cashier redirects

---

resources/views/partials/layout.blade.php

I've made some improvements to the title tag on the documentation pages, so now it dynamically displays the Laravel version.
These changes improve how the docs links are displayed in search engines and in browsers.
I've added a check to see if the $currentVersion variable is set, and it's currently being set only by the DocsController.
When $currentVersion is master, it adds "Upcoming" to title:
> Installation - Laravel Upcoming - The PHP Framework For Web Artisans
And when $currentVersion is set to a specific version, it adds that version to the title:
> Installation - Laravel 10.x - The PHP Framework For Web Artisans

Update documentation page title to display dynamic Laravel version

---

package-lock.json
resources/views/docs.blade.php

The Laravel version warning callout is missing a wrapper resulting in additional margin after the paragraph.
By adding a wrapper with the "callout" class this issue can be resolved.

Fix Laravel version warning callout

---

resources/views/partials/footer.blade.php

Since there's a neat https://discord.gg/laravel link available (which is also used in the contribution guide), I think it's beneficial to use the vanity link in the footer as well. This makes it easier to remember the invite link as well.

Use the Discord vanity URL in footer link

---

resources/views/components/header-news-bar.blade.php

Following https://github.com/laravel/laravel.com/commit/e78e766c827fce9400e1613caa84d45edebaa835 the value `merch` is also removed from the selectable values.

Remove merch from random values

---

.gitignore
app/Console/Kernel.php
build/docs.sh
build/hashes/.gitignore
config/services.php

- Requires `jq` to be installed on the server.
- Requires `CLOUDFLARE_ZONE` and `CLOUDFLARE_TOKEN` env variables to be set.

Proof of concept: Bust cloudflare cache

---

bin/checkout_latest_docs.sh

This quick PR adds the missing 11.x version tag to the `DOCS_VERSIONS` array in the `checkout_latest_docs.sh` script.

Update checkout_latest_docs.sh to add 11.x

---

resources/views/components/header-news-bar.blade.php

Just fixing the typo of "Dallas"

Fix typo in header-news-bar about Laracon

---

resources/views/partials/layout.blade.php

The preloading technique we have employed uses a 65ms delay before loading a link once hovered.
I think we can just preload the link as soon as it is hovered. This seems to be the way most other preloading techniques work and I think we can safely do this on the Laravel docs.
In fact, a lot of other preloading techniques just preload any link as soon as it enters the _viewport_ (which I feel is a little too much - although we can do it).

Loading links as soon as hovered

---

resources/views/components/header-news-bar.blade.php
resources/views/docs.blade.php

With our recent changes to caching, we lost the per-load randomness of the header banner and side bar promotion.
This PR restores the per-load randomness to ensure that the one banner / side bar add is not stuck on each page for an extended period of time and get an equal share of views. It achieves this by pushing the randomness into JavaScript.

Restore per-load randomness

---

package-lock.json
resources/views/components/button/primary.blade.php
resources/views/components/forms/checkbox.blade.php
resources/views/components/forms/input.blade.php
resources/views/components/forms/textarea.blade.php
resources/views/docs.blade.php
tailwind.config.js

This PR fixes some broken input styles after #358 introduced `@tailwindcss/forms` plugin.
Also fixes all the primay buttons with `href` attributes
**Before**
**After**

Fix broken input styles and broken buttons

---

resources/views/partials/header.blade.php

Fix mobile navigation padding overlap
- Adjusted top padding in mobile navigation menu to prevent overlap between logo and close button
- Previous behaviour caused the logo and close button to collide on mobile devices
Before
After

Fix mobile navigation overlap
