public/assets/css/laravel.css
resources/assets/sass/components/_slide-menu.scss

Here's a screenshot of the flash of unstyled content happening before dom ready:

Fixed flash of unstyled content before dom ready in slide-menu.scss

---

app/Documentation.php
app/Http/Controllers/DocsController.php
resources/views/partials/switcher.blade.php

Hey, well basically, the idea is when you are located in the docs section.
You are reading in some specific section, e.g http://laravel.com/docs/4.2/homestead and you want to switch to another version such 5.0, it redirects you to http://laravel.com/docs/5.0
What I consider is that it should keep the section (in this example, homestead) with the new version selected (http://laravel.com/docs/5.0/homestead)
What do you think?
cc @GrahamCampbell

Docs section: keep the current section when switch between versions

---

resources/views/partials/main-nav.blade.php

Hi!
I thought that would be handy if the API documentation version would stick with the current documentation version.
Exemple:
laravel.com/docs/4.1
laravel.com/api/4.1
The modification seems to work great.
Any thoughts?

Link to the right API version

---

resources/assets/sass/components/_nav.scss

Added paddings to navbar links to be more user-friendly and easy clickable.

Add padding to nav links to make it "more clickable"

---

resources/views/app.blade.php

I like to have a link to the docs on my phone, but it currently just shows a screenshot of the site, and doesn't let you select a custom icon.
this commit tells IOS to use the logo image when people add any laravel.com page to their home screen.

add apple touch icon link to site

---

resources/assets/sass/core/_base.scss

The font smoothing makes it very hard to read. Specially since the text is very thin to begin with. 
The above example show how it looked before this PR and after. Font smoothing makes mare sense with a dark background and bright font but the other way around just makes it harder to read. I guess it depends on the use case.

Remove font smoothing

---

resources/assets/js/laravel.js

`typeahead.js` has its own value store so clearing the value (`val()`) of the input is only aesthetic. This clears the input correctly and the search icon will now reappear after clicking the X cross.

Fixes clearing the search

---

build/sami/sami.php

This adds "View source" links for every class (FriendsOfPHP/Sami#91):
In a future version of Sami each class method will get a link, too
(FriendsOfPHP/Sami#186):

Configure remote repository for Sami API documentation

---

composer.json
composer.lock

This will add the links promised in #54 to the documentation.
Note that this commit updates other dependencies as well since Sami now requires a newer version of twig.

Update Sami to v3.2.*

---

app/Http/Controllers/DocsController.php
resources/views/app.blade.php

If the page hasn't changed, point the canonical link to the latest version, to keep the search rank. Only if no same page is found, use the no-index. (Re https://twitter.com/taylorotwell/status/762380829800538113 )
(Could be improved with mapping old->new, but it tedious to keep in sync perhaps).
/cc @casperbakker

Use canonical when possible

---

readme.md

To get the project running locally, I had to figure out where the documentation content was coming from. And since the readme was the default Laravel readme, I changed it to give some understanding about this project and how to get the docs working.
Could be handy for the next guy or girl that wants to contribute to the website.

Creates a distinct readme for the laravel.com project

---

resources/views/app.blade.php

While browsing main page or a 404 request, an Uncaught AlgoliaSearchError is generated:
```javascript
algoliasearch.js:6866
Uncaught AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
```
because algoliasearch.js is always included via gulp, but algolia credentials are only loaded on docs* 
This fix ensures credentials are always loaded in the main template, despite the URI.

Fix for Uncaught AlgoliaSearchError

---

resources/assets/sass/components/_nav.scss

Tweak Search input field for better usability by a bigger click area.
Used .twitter-typeahead class, but would be nice if we find a way to change the Typeahead wrapper for a more general class name.

Tweak Search input field

---

resources/assets/js/laravel.js

As far as I can tell, because the documentation index is cached, doing this client-side via JavaScript is the simplest way of implementing request at laravel/docs#2738

Add highlighting of current page link in docs

---

resources/assets/sass/components/_prism.scss
resources/assets/sass/core/_settings.scss

Use `Operator Mono` or `Fira Code` if it's available on the user's system.

Use custom local code font when available

---

resources/views/errors/404.blade.php

On mobile, the menu icon does not trigger the slide menu on the 404 page specifically. I noticed that the scotchPanel is referencing the `#slide-menu` element, which appears to be missing in the template. I copied the nav section from the marketing and docs template.

added missing slide menu to 404 page

---

resources/assets/sass/content/_docs.scss

Now the hash sign is below the title, which looks not so nice in my opinion, I suggest removing the top positioning so that this sign is aligned vertically.
Before:
After:

Vertical align hash sign

---

resources/assets/sass/components/_nav.scss

Fix positioning for community dropdown

---

resources/assets/js/laravel.js

With the `'keyup'` option specified, the key binding doesn't work very well with non-american (?) keyboard layouts where you have to press `Shift + 7` to get the `/` character. Simply removing the "keyup" option fixes the issue.

Fixed search key binding

---

resources/assets/js/laravel.js

So, it seems #121 introduced a bug which causes "/" to being typed into the search field at initial focus. 😳  
Calling `preventDefault` on the keyboard event fixes the issue.

Prevent "/" from being typed

---

resources/assets/sass/components/_slide-menu.scss

This PR comes from the original https://github.com/laravel/laravel.com/pull/123/ 
It specifically focuses on fixing the mobile menu flash by implementing a mobile first css structure

[Bug Fix] Prevents mobile menu flash on page load

---

resources/assets/js/laravel.js
resources/views/app.blade.php

This is related to the list of changes https://github.com/laravel/laravel.com/pull/123
It specifically fixes a flash of un-styled content on the global site search box before algolia and typeahead have been initialised.

[Bug Fix] FOUC for search box whilst page is loading

---

resources/assets/js/laravel.js

As per [your suggestion](https://twitter.com/taylorotwell/status/871775692639264770) have added the shortcut since you have denied [our initial proposal](https://github.com/laravel/internals/issues/626)
- **`Ctrl+b`** or **`Command + b`** now expands all the sections in the docs sidebar.
- Decided on this particular shortcut since it's the closest to sublime's `ctrl+k+b` to open the sidebar but made it more shorter so it's more convenient.
- Open for further suggestions & discussion :blush:

Keyboard shortcut added to expand all sections in the sidebar

---

.gitignore
resources/assets/js/laravel.js
resources/views/docs.blade.php

As per your request: https://twitter.com/taylorotwell/status/882792854715854850
- Toggles classes of all headers to expand and collapse
- Saves state into LocalStorage if available (no polyfill but feature detection)
- Loads previous state if available
- Open for suggestions or edits to match code style 😄 
Small preview! https://static.ozairpatel.com/4g0go.mp4

Docs "Expand All" button with LocalStorage support

---

resources/assets/sass/content/_community.scss
resources/views/community-partner-kirschbaum.blade.php
resources/views/partners.blade.php

This PR addresses three issues:
1) Fixes Kirschbaum Development Group CTA on mobile devices.
2) Fixes a padding issue on the partners landing page for mobile devices.
3) Adds padding between the social media links and the descriptive text on the partners template.

Fixes for the partners pages on mobile devices

---

resources/views/marketing.blade.php
resources/views/partials/browser.blade.php

I know it's a minor change, and you probably have a good reason to put it there. But I would definitely sleep better at night, knowing that I at least tried to fix it 😉

Fix excessive spaces in code examples

---

bootstrap/helpers.php
routes/web.php

When running a cache command like `config:cache` or `route:cache`, a fresh application will be created and `routes/web.php` will be included twice, then the command will fail.

Fix redeclare markdown() and DEFAULT_VERSION constant

---

build/docs.sh

Currently, changes to the 4.2 docs do not get pulled into the Laravel.com website. PR examples include: #3388 (https://github.com/laravel/docs/commit/5d4c6621b09ca45c31754f86cac2a810ec081aad), #3328 (https://github.com/laravel/docs/commit/5f52dd18adb3ad9c126eb95abfa8ad7123c1b48e) and #2918 (https://github.com/laravel/docs/commit/d1daa182680ce2aafe3a7b81c442f3a2d744a980).
Also, the sidebar doesn't include the collapsable feature.

Allow 4.2 docs to be updated

---

resources/assets/js/laravel.js

As some others pointed out [here](https://github.com/laravel/docs/issues/3277) and [here](https://github.com/laravel/docs/issues/3284), it's rather bothersome to not being able to cmd+click on sidebar menu links.
This pull request prevents the sidebar from collapsing when hitting keys that don't affect the sidebar (enter, left arrow, right arrow).

Prevent sidebar to be collapsed when hitting keys

---

resources/assets/sass/components/_nav.scss

I use a custom gtk theme under Ubuntu Mate. Styling from the gtk theme is applied  to the search box in Firefox. This PR forces the background of the search input to be white.
Before:
After:

Force searchbox to be white

---

app/Http/Controllers/DocsController.php
resources/assets/sass/content/_404.scss
resources/views/partials/doc-missing.blade.php

Ok - this is another attempt at smarter document 404's.
Now we just display the same 404 message, but with the doucment menu available.
**Current behavior:**
**New behavior:**
Original 404 page is unchanged for the rest of the site - it will display the same.

Smarter 404's version 2

---

resources/assets/sass/laravel.scss

Adjust the line-height and em value to make the Carbon ad more compact
and take less vertical space due to sidebar > li line-height is set to
30px.
Check out the preview at https://d.pr/i/OQ3zhj

Fix Carbon Line Height

---

resources/assets/sass/content/_community.scss

`.flag` is used elsewhere in the docs. Fixes https://github.com/laravel/docs/issues/4152.

New flag styling should apply only to partners

---

app/Http/Controllers/DocsController.php

Unless there is a reason for getting the array keys first, we should use the native PHP function for this.

Use array_key_exists

---

composer.json
composer.lock

The league/commonmark package was previously swapped and replaced by erusev/parsedown-extra, but its dependency was never removed.
This PR is courtesy of @JeffreyWay and his new Laracasts' course on How to Read Code.

Remove unused league/commonmark dependency

---

resources/assets/sass/components/_slide-menu.scss
resources/views/docs.blade.php

Currently, the version switch in the Documentation section disappears on screens with a width of 500 pixels or fewer. As a result, it is not possible to view documentation for versions older than the current version, when viewing on most mobile screens.
This PR simply takes the existing version switcher functionality and adds it into the sidebar, for screens with a width of 500 pixels or fewer. The code changes to implement this are purposefully very simple, reusing the existing version switch code in full - with only slight style changes to account for positioning and the change in background color.
This PR only impacts the sidebar, of the Documentation section, when viewing from a device with 500 pixels or fewer width. All other parts of the site remain unchanged.
**<500px Docs Sidebar …

Add docs version switcher to sub 500 px mobile screens

---

resources/assets/sass/components/_slide-menu.scss
resources/views/docs.blade.php

The new version switcher that appear in the sidebar on <500px screens doesn't work well with the smallest screens, like an iPhone SE. This PR changes the appearance of the version switcher to fix this problem. I experimented with a few different ways of fixing this, and have settled on this as the best of the bunch.
Note that I did experiment with simply showing all of the versions in a list, similar to the other doc sections, but I felt that was both too confusing and also took up too much vertical real estate.

Change mobile version switcher appearance for smallest screens

---

app/Http/Controllers/DocsController.php

Fixes redirect when invalid docs version is specified. For example, docs/4.1 was redirecting to docs/5.7/4.1. Also preserve requested page (i.e., docs/4.1/releases will properly go to docs/5.7/releases instead of docs/5.7/4.1)

Fix invalid version redirect

---

package.json
public/assets/css/laravel.css
public/mix-manifest.json
resources/assets/sass/components/_packages.scss
resources/views/marketing.blade.php

Before this PR the alignment of the packages list on the homepage wasn't good if the text describing the packages wasn't the same length.
It's now fix, the alignment will  stay good no matter the length of the text.

Update the packages component

---

resources/views/partials/main-nav.blade.php

Add blog to Ecosystem links. I saw there were already https://github.com/laravel/laravel.com/pull/209 and https://github.com/laravel/laravel.com/pull/210 but this one just adds link to Ecosystem section - quite useful to know about official blog to anyone who is new in Laravel community and don't follow Twitter 😄

Add link to Laravel blog

---

resources/views/marketing.blade.php

Since v10 of Laravel Cashier, Braintree is no longer built-in so I've removed it from the description of Cashier on the homepage.
However, Braintree does have support, but only from a separate package which maintenance on has been abandoned.

Braintree integration is no longer built-in

---

resources/views/community-partner-kirschbaum.blade.php

Updated the LinkedIn url on the [Kirschbaum partner page](https://laravel.com/partner/kirschbaum-development-group).

Updated LinkedIn url on the Kirschbaum partner page

---

readme.md

this repo is the old laravel.com site.  we will state that so people know to no longer use it, and link them to the new one.
maybe also put the repo in "Read Only" mode as a further indicator people should not be PRing to this repo?

link to current larvel.com site repo
